filetype off

if has("vim_starting")
  set nocompatible
  set runtimepath+=~/.vim/bundle/neobundle.vim
endif

call neobundle#begin(expand('~/.vim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim'

call neobundle#end()

NeoBundle 'scrooloose/syntastic'
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/vimshell.vim'
NeoBundle 'nathanaelkane/vim-indent-guides/'
NeoBundle 'vim-scripts/Align'
NeoBundle 'vim-scripts/javacomplete'
NeoBundle 'vim-scripts/taglist.vim'
NeoBundle 'bling/vim-airline'
NeoBundle 'tpope/vim-abolish'
" Hakkellのシンタックスハイライト
NeoBundle 'raichoo/haskell-vim'
" vimからのコンソール実行
NeoBundle 'thinca/vim-quickrun'

NeoBundle 'Shougo/vimproc.vim', {
\ 'build' : {
\     'windows' : 'tools\\update-dll-mingw',
\     'cygwin' : 'make -f make_cygwin.mak',
\     'mac' : 'make -f make_mac.mak',
\     'linux' : 'make',
\     'unix' : 'gmake',
\    },
\ }

"colors
NeoBundle 'altercation/vim-colors-solarized'
NeoBundle 'chriskempson/vim-tomorrow-theme'


" Installation check.
NeoBundleCheck

filetype on
filetype plugin indent on

